w001/tracks/config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

w001/tracks/app/models/todos/calendar.rb
module Todos
  class Calendar

    attr_reader :user, :included_tables

    def initialize(user)
      @user = user
      @included_tables = Todo::DEFAULT_INCLUDES
    end

    def projects
      user.projects
    end

    def due_today
      actions.due_today
    end

    def due_this_week
      actions.due_between(today, end_of_the_week)
    end

    def due_next_week
      actions.due_between(end_of_the_week, end_of_next_week)
    end

    def due_this_month
      actions.due_between(end_of_next_week, end_of_the_month)
    end

    def due_after_this_month
      actions.due_after(end_of_the_month)
    end

    def today
      @today ||= Time.zone.now
    end

    def end_of_the_week
      @end_of_the_week ||= today.end_of_week
    end

    def end_of_next_week
      @end_of_next_week ||= end_of_the_week + 7.days
    end

    def end_of_the_month
      @end_of_the_month ||= today.end_of_month
    end

  private

    def actions
      user.todos.not_completed.includes(included_tables).reorder("due")
    end

  end
end

w001/tracks/app/helpers/todos_helper.rb
module TodosHelper

  # === helpers for rendering container

  def empty_message_holder(container_name, show, title_param=nil)
    content_tag(:div, :id => "no_todos_in_view", :class => "container #{container_name}", :style => "display:" + (show ? "block" : "none") ) do
      content_tag(:h2) { t("todos.no_actions.title", :param=>title_param) } +
      content_tag(:div, :class => "message") do
        content_tag(:p) { t("todos.no_actions.#{container_name}", :param=>title_param) }
      end
    end
  end

  def todos_container_empty_message(container_name, container_id, show_message)
    content_tag(:div, :id=>"#{container_id}-empty-d", :style=>"display:#{show_message ? 'block' : 'none'}") do
      content_tag(:div, :class=>"message") do
        content_tag(:p) do
          t("todos.no_actions.#{container_name}")
        end
      end
    end
  end

  def show_grouped_todos(settings = {})
    collection = (@group_view_by == 'context') ? @contexts_to_show : @projects_to_show
    render(:partial => collection, :locals => { :settings => settings.reverse_merge!({
      :collapsible => true,
      :show_empty_containers => @show_empty_containers,
      :parent_container_type => @group_view_by
    })})
  end

  def default_collection_settings
    {
      :suppress_context => false,
      :suppress_project => false,
      :collapsible => false,
      :append_descriptor => nil,
      :parent_container_type => nil,
      :show_empty_containers => true
    }
  end

  def show_done_todos(done_todos, settings={})
    settings[:container_name] = "completed"
    settings[:link_in_header] = link_to(t('common.show_all'), determine_done_path)

    render :partial => 'todos/collection',
      :object => done_todos,
      :locals => {:settings => settings.reverse_merge!(default_collection_settings)}
  end

  def show_completed_todos_for(period, collection)
    settings = {
      :parent_container_type => "completed",
      :container_name => "completed_#{period}",
      :title => t("todos.completed_#{period}"),
      :show_empty_containers => true
    }

    render :partial => "todos/collection",
      :object => collection,
      :locals => { :settings => settings}
  end

  def show_hidden_todos(hidden_todos, settings={})
    settings[:container_name] = "hidden"

    render :partial => 'todos/collection',
      :object => hidden_todos,
      :locals => {:settings => settings.reverse_merge!(default_collection_settings)}
  end

  def show_deferred_pending_todos(deferred_todos, pending_todos, settings={})
    settings[:pending] = pending_todos
    settings[:container_name]="deferred_pending"

    render :partial => "todos/collection",
      :object => deferred_todos+pending_todos,
      :locals => {:settings => settings.reverse_merge!(default_collection_settings)}
  end

  def show_todos_without_project(todos_without_project, settings = {})
    render :partial => 'todos/collection',
      :object => todos_without_project,
      :locals => {:settings => settings.reverse_merge!({
        :collapsible => true,
        :container_name => "without_project",
        :parent_container_type => "home"
        })
      }
  end

  def todos_container(settings={})
    settings.reverse_merge!({
      :id => "#{settings[:container_name]}_container",
      :class => "container #{settings[:container_name]}",
      })

    if settings[:collapsible]
      settings[:class] += " collapsible"
    end

    content_tag(:div,
      :class=>settings[:class],
      :id=>settings[:id],
      :style => "display:" + (settings[:show_container] ? "block" : "none")) do
      yield
    end
  end

  def todos_container_header(settings={})
    settings.reverse_merge!({
        :title => t("todos.actions.#{settings[:parent_container_type]}_#{settings[:container_name]}", :param => settings[:title_param])
      })
    header = settings[:link_in_header].nil? ? "" : content_tag(:div, :class=>"link_in_container_header"){settings[:link_in_header]}
    header += content_tag(:h2) do
      toggle = settings[:collapsible] ? container_toggle("toggle_#{settings[:id]}") : ""
      "#{toggle} #{settings[:title]} #{settings[:append_descriptor]}".html_safe
    end
    header.html_safe
  end

  def todos_container_items(collection, settings={})
    settings.reverse_merge!({:id => "#{settings[:container_name]}"})
    # do not pass :class to partial locals
    settings.delete(:class)

    content_tag(:div, :id =>settings[:id]+"_items", :class=>"items toggle_target") do
      todos_container_empty_message(settings[:container_name], settings[:id], collection.empty?) +
      render(:partial => "todos/todo", :collection => collection, :locals => settings)
    end
  end

  def todos_calendar_container(period, collection)
    render :partial => 'todos/collection',
      :object => collection,
      :locals => {:settings => {
        :collapsible => false,
        :show_empty_containers => true,
        :container_name => "#{period}",
        :title =>t("todos.calendar.#{period}", :month => l(Time.zone.now, :format => "%B"), :next_month => l(1.month.from_now, :format => "%B"))
        }
      }
  end

  # === helpers for rendering a todo

  def remote_star_icon(todo=@todo)
    link_to( image_tag_for_star(todo),
      toggle_star_todo_path(todo),
      :class => "icon star_item", :title => t('todos.star_action_with_description', :description => todo.description))
  end

  def remote_edit_button(todo=@todo)
    link_to(
      image_tag("blank.png", :alt => t('todos.edit'), :align => "absmiddle", :id => dom_id(todo, "edit_icon"), :class => 'edit_item'),
      edit_todo_path(todo),
      :class => "icon edit_item",
      :id => dom_id(todo, "icon_edit"),
      :title => t('todos.edit_action_with_description', :description => todo.description))
  end

  def remote_delete_menu_item(todo)
    return link_to(
      t('todos.delete'),
      {:controller => 'todos', :action => 'destroy', :id => todo.id},
      :class => "icon_delete_item",
      :id => dom_id(todo, "delete"),
      :x_confirm_message => t('todos.confirm_delete', :description => todo.description),
      :title => t('todos.delete_action'));
  end

  def remote_defer_menu_item(days, todo)
    url = {:controller => 'todos', :action => 'defer', :id => todo.id, :days => days,
      :_source_view => (@source_view.underscore.gsub(/\s+/,'_') rescue "")}
    url[:_tag_name] = @tag_name if @source_view == 'tag'

    options = {:x_defer_alert => false, :class => "icon_defer_item icon_defer_#{days}_item", :id => "defer_#{days}_#{dom_id(todo)}" }
    if todo.due
      futuredate = (todo.show_from || todo.user.date) + days.days
      if futuredate.at_midnight > todo.due.at_midnight
        options[:x_defer_alert] = true
        options[:x_defer_date_after_due_date] = t('todos.defer_date_after_due_date')
      end
    end

    return link_to(t('todos.defer_x_days', :count => days), url, options)
  end

  def remote_delete_dependency(todo, predecessor)
    link_to(
      image_tag("blank.png", :title => t('todos.remove_dependency'), :align => "absmiddle", :class => "delete_item"),
      remove_predecessor_todo_path(todo),
      {:class => "delete_dependency_button", :x_predecessors_id => predecessor.id}
    )
  end

  def remote_promote_to_project_menu_item(todo)
    url = {:controller => 'todos', :action => 'convert_to_project', :id => todo.id,
      :_source_view => (@source_view.underscore.gsub(/\s+/,'_') rescue "")}
    url[:_tag_name] = @tag_name if @source_view == 'tag'

    link_to(t('todos.convert_to_project'), url, {:class => "icon_item_to_project", :id => dom_id(todo, "to_project")})
  end

  def attachment_image(todo)
    link_to(
      image_tag('blank.png', width: 16, height: 16, border:0),
      todo.attachments.first.file.url,
      {:class => 'todo_attachment', title: 'Get attachments of this todo'}
    )
  end

  def collapsed_notes_image(todo)
    link = link_to(
      image_tag( 'blank.png', :width=>'16', :height=>'16', :border=>'0' ),
      "#",
      {:class => 'show_notes', :title => 'Show notes'})
    notes = content_tag(:div, {
      :class => "todo_notes",
      :id => dom_id(todo, 'notes'),
      :style => "display:none"}) { raw render_text(todo.notes) }
    return link+notes
  end

  def collapsed_successors_image(todo)
    link = link_to(image_tag( 'blank.png', :width=>'16', :height=>'16', :border=>'0' ), "#", {:class => 'show_successors', :title => 'Show successors'})
    successors = content_tag(:div, {:class => "todo_successors", :id => dom_id(todo, 'successors'), :style => "display:none"}) do
      render :partial => "todos/successor", :collection => todo.pending_successors,
        :locals => { :parent_container_type => parent_container_type, :suppress_dependencies => true, :predecessor => todo }
    end
    return link+successors
  end

  def image_tag_for_recurring_todo(todo)
    return link_to(
      image_tag("recurring16x16.png"),
      recurring_todos_path,
      :class => "recurring_icon", :title => recurrence_pattern_as_text(todo.recurring_todo))
  end

  def image_tag_for_star(todo)
    image_tag("blank.png", :title =>t('todos.star_action'), :class => "todo_star"+(todo.starred? ? " starred":""), :id => "star_img_"+todo.id.to_s)
  end

  def remote_toggle_checkbox(todo=@todo)
    check_box_tag("mark_complete_#{todo.id}", toggle_check_todo_path(todo), todo.completed?, :class => 'item-checkbox',
      :title => todo.pending? ? t('todos.blocked_by', :predecessors => todo.uncompleted_predecessors.to_a.map(&:description).join(', ')) : "", :readonly => todo.pending?)
  end

  def remote_mobile_checkbox(todo=@todo)
    form_tag toggle_check_todo_path(@todo, :format => 'm'), :method => :put, :class => "mobile-done", :name => "mobile_complete_#{@todo.id}" do
      check_box_tag('_source_view', 'todo', @todo && @todo.completed?, "onClick" => "document.mobile_complete_#{@todo.id}.submit()")
    end
  end

  def date_span(todo=@todo)
    if todo.completed?

w001/tracks/app/views/todos/_collection.m.erb
<%=
  settings[:show_container] = !collection.empty? || settings[:show_empty_containers]

  todos_container(settings) do
    todos_container_header(settings) +
    todos_container_items(collection, settings)
  end
%>

w001/tracks/app/views/todos/_edit_form.html.erb
<% todo = edit_form -%>
<%= form_for(todo, :html=> { :name=>'todo', :id => dom_id(@todo, 'form'), :class => 'inline-form edit_todo_form' }) do |t|%>
  <div id="edit_error_status">
  <% if todo.errors.any? -%>
    <ul>
      <% todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end -%>
  </div>

  <%= t.hidden_field( "id" ) -%>
  <%= source_view_tag( @source_view ) -%>
  <%= content_tag(:input, "", :type=>"hidden", :name=>"_tag_name", :value=>"#{@tag_name}") if @tag_name -%>

  <label for="<%= dom_id(@todo, 'description') %>"><%= t('common.description') %></label>
  <%= t.text_field( "description", "size" => 30, "maxlength" => 100) %>

  <label for="<%= dom_id(@todo, 'notes') %>"><%= t('common.notes') %></label>
  <%= t.text_area( "notes", "cols" => 29, "rows" => 4) %>

  <div class="project_input">
    <label for="<%= dom_id(@todo, 'project_name') %>"><%= t('common.project') %></label>
    <input id="<%= dom_id(@todo, 'project_name') %>" name="project_name" autocomplete="off" size="30" type="text" value="<%= @todo.project.nil? ? '' : h(@todo.project.name) %>" />
  </div>

  <div class="context_input">
    <label for="<%= dom_id(@todo, 'context_name') %>"><%= t('common.context')  %></label>
    <input id="<%= dom_id(@todo, 'context_name') %>" name="context_name" autocomplete="off" size="30" type="text" value="<%= h @todo.context.name %>" />
  </div>

  <label class="tag_list_label" for="<%= dom_id(@todo, 'tag_list') %>"><%= t('todos.tags') %></label>
  <%= text_field_tag 'tag_list', tag_list_text, :id => dom_id(@todo, 'tag_list'), :size => 30 %>

  <div class="due_input">
    <label for="<%= dom_id(@todo, 'due_label') %>"><%= Todo.human_attribute_name('due') %></label>
    <%= date_field_tag("todo[due]", dom_id(@todo, 'due'), format_date(@todo.due)) %>
    <a href="#" id="<%= dom_id(@todo, 'due_x') %>" class="date_clear" title="<%= t('todos.clear_due_date') %>">
      <%= image_tag("blank.png", :alt => t('todos.clear_due_date'), :class => "delete_item") %>
    </a>
  </div>

  <div class="show_from_input">
    <label for="<%= dom_id(@todo, 'show_from') %>"><%= t('todos.show_from') %></label>
    <%= date_field_tag("todo[show_from]", dom_id(@todo, 'show_from'), format_date(@todo.show_from)) %>
    <a href="#" id="<%= dom_id(@todo, 'show_from_x') %>" class="date_clear" title="<%= t('todos.clear_show_from_date') %>">
      <%= image_tag("blank.png", :alt => t('todos.clear_show_from_date'), :class => "delete_item") %>
    </a>
  </div>

  <div class="depends_on">
    <label for="predecessor_ul"><%= Todo.human_attribute_name('predecessors')%></label>
    <div class="selected_predecessors">
      <ul class="predecessor_list" id="predecessor_ul" style="display:<%= @todo.predecessors.empty? ? "none" : "block"%>">
      </ul>
    </div>
    <label id="label_for_predecessor_input" for="predecessor_input" style="display:none"><%= t('todos.add_another_dependency')%></label>
    <%= text_field_tag "predecessor_input", nil, :size => 30 %>
    <%= hidden_field_tag "predecessor_list", @todo.predecessors.map{|t| t.id.to_s}.join(', ') %>
  </div>


  <div class="submit_box">
    <div class="widgets">
      <button type="submit" class="positive" id="<%= dom_id(@todo, 'submit') %>">
        <%=image_tag("accept.png", :alt => "") %>
        <%= t('common.update') %>
      </button>
      <a href="#" class="negative">
        <%=image_tag("cancel.png", :alt => "") %>
        <%= t('common.cancel') %>
      </a>
    </div>
  </div>

<% end %>

w001/tracks/app/views/todos/_mobile_actions.m.erb
<% if @not_done_todos.empty? -%>
<p><%= t('todos.no_actions.not_done') %></p>
<% else -%>
<%= render :partial => @contexts_to_show -%>
<% end -%>
<% unless @done.nil? -%>
<div id="completed_container">
<h2><%= t('todos.completed_actions') %></h2>
<ul class="c">
<%= render :partial => @done %>
</ul>
</div>
<% end %>

w001/tracks/app/views/todos/_new_multi_todo_form.html.erb
<%- todo = new_multi_todo_form -%>

<div id="todo_multi_add" style="display:none">
  <%= form_for(todo, :html=> { :id=>'todo-form-multi-new-action', :name=>'todo', :class => 'inline-form' }) do |t| %>
    <input id="default_project_name_id" name="default_project_name" type="hidden" value="<%=h @initial_project_name-%>" />
    <input id="default_context_name_id" name="default_context_name" type="hidden" value="<%=h @initial_context_name-%>" />

    <div id="multiple_error_status">
    <% if todo.errors.any? -%>
      <ul>
        <% todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end -%>
    </div>

    <label for="todo_notes"><%= t('shared.multiple_next_actions') %></label>
    <%= text_area_tag( "todo[multiple_todos]", "", :cols => 29, :rows => 6 ) %>

    <label for="todo_project_name"><%= t('shared.project_for_all_actions') %></label>
    <input id="multi_todo_project_name" name="project_name" autocomplete="off" size="30" type="text" value="<%=h @initial_project_name %>" />
    <div class="page_name_auto_complete" id="project_list" style="display:none"></div>

    <label for="todo_context_name"><%= t('shared.context_for_all_actions') %></label>
    <input id="multi_todo_context_name" name="context_name" autocomplete="off" size="30" type="text" value="<%=h @initial_context_name %>" />
    <div class="page_name_auto_complete" id="context_list" style="display:none"></div>

    <label for="tag_list"><%= t('shared.tags_for_all_actions') %></label>
    <%= hidden_field_tag "initial_tag_list", @initial_tags%>
    <%= text_field_tag "multi_tag_list", @initial_tags, :name=>:tag_list, :size => 30 %>
    <%= content_tag("div", "", :id => "tag_list_auto_complete", :class => "auto_complete") %>

    <%= check_box_tag('todos_sequential', 'true', false) %>
    <label for="todos_sequential"><%= t('shared.make_actions_dependent') %></label>

    <div class="submit_box">
      <div class="widgets">
        <button type="submit" class="positive" id="todo_multi_new_action_submit">
          <%=  image_tag("accept.png", :alt => "") %><%= t('shared.add_actions') %>
        </button>
      </div>
    </div>

  <% end -%>

</div>

w001/tracks/app/views/todos/_update_has_errors.js.erb
animate: function() {
  TracksPages.show_edit_errors(<%=object_name%>.html_for_error_messages());
},
html_for_error_messages: function() {
  return "<%= escape_javascript(get_list_of_error_messages_for(@todo)) %>";
}

w001/tracks/app/views/todos/check_deferred.js.erb
<% unless @due_tickles.empty? -%>
  TracksPages.page_inform("<%=t('todos.tickler_items_due', :count => @due_tickles.length)%>");
<% end -%>

w001/tracks/app/views/todos/error.js.erb
<%
# TODO: is this ever called?
-%>
TracksPages.page_error("<%=@error_message || t('common.server_error')%>");

w001/tracks/app/views/todos/index.text.erb
<%= render :partial => @contexts, :locals => { :todos => @todos, :not_done_todos => @not_done_todos } %>

w001/tracks/app/views/todos/list_deferred.m.erb
<% if @count == 0 -%>
<div class="message"><p><%= t('todos.no_deferred_actions') %></p></div>
<% end -%>
<%= render :partial => @contexts, :locals => { :collapsible => true } -%>

w001/tracks/app/views/todos/new.m.erb
<%= form_tag todos_path(:format => 'm'), :method => :post do %>
  <%= render :partial => 'edit_form' %>
  <p class="text-right"><input type="submit" class="btn" value="<%= t('common.create') %>" accesskey="#" /></p>
<% end -%>
<%= link_to t('common.back'), @return_path %>

w001/tracks/app/views/todos/show.m.erb
<h2><%= t('common.description') %></h2>
<%= @todo.description %><br/>

<h2><Actions><%= t('common.actions') %></h2>

<form method="get" action="<%= edit_todo_path(@todo, :format => :m)%>">
	<button class="btn"><%=t('todos.edit_action')%></button>
	<input type="hidden" name="_method" value="put" />
</form>

<form method="post" action="<%=toggle_star_todo_path(@todo, :format=>:m)%>">
	<button class="btn"><%=t('todos.star_action')%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

<form method="post" action="<%=toggle_check_todo_path(@todo, :format=>:m)%>">
	<button class="btn"><%= t('todos.mark_complete')%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

<form method="post" action="<%=defer_todo_path(@todo, :format=>:m, :days => 1)%>">
	<button class="btn"><%=t('todos.defer_x_days', :count => 1)%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

<form method="post" action="<%=defer_todo_path(@todo, :format=>:m, :days => 2)%>">
	<button class="btn"><%=t('todos.defer_x_days', :count => 2)%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

<form method="post" action="<%=defer_todo_path(@todo, :format=>:m, :days => 3)%>">
	<button class="btn"><%=t('todos.defer_x_days', :count => 3)%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

<form method="post" action="<%=defer_todo_path(@todo, :format=>:m, :days => 7)%>">
	<button class="btn"><%=t('todos.defer_x_days', :count => 7)%></button>
	<input type="hidden" name="_method" value="put" />
	<%= token_tag %>
</form>

w001/tracks/app/views/todos/tag.m.erb
<div id="display_box">
<% if @not_done_todos.empty? -%>
<div class="container context">
<h2><%= t('todos.no_actions_found_title') %></h2>
<div class="message"><%= t('todos.no_actions_with', :tag_name => @tag_title) %></div>
</div>
<% end -%>
<%= render :partial => @contexts_to_show -%>
<h2><%= t('todos.deferred_actions_with', :tag_name=> @tag_title) %></h2>
<% unless (@deferred.nil? or @deferred.size == 0)  -%>
<ul class="c">
<%= render :partial => @deferred, :locals => { :parent_container_type => "tag" } -%>
</ul>
<% else -%>
<%= t('todos.no_deferred_actions_with', :tag_name => @tag_title) %>
<% end -%>
<h2><%= t('todos.completed_actions_with', :tag_name => @tag_title) %></h2>
<% unless (@done.nil? or @done.size == 0) -%>
<ul class="c">
<%= render :partial => @done, :locals => { :parent_container_type => "tag" } %>
</ul>
<% else -%>
<%= t('todos.no_completed_actions_with', :tag_name => @tag_title) %>
<% end -%>
</div>

w001/tracks/app/views/todos/update.js.erb
<%- object_name = unique_object_name_for("update_todo_#{@todo.id}") -%>
var <%=object_name%> = {
  <%= render :partial => (@saved ? "update_successful" : "update_has_errors"), locals: {object_name: object_name} %>
}
<%=object_name%>.animate();