w001/tracks/config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

w001/tracks/app/models/stats/actions.rb
module Stats
  class Actions

    SECONDS_PER_DAY = 86400;

    attr_reader :user
    def initialize(user)
      @user = user
    end

    def ttc
      @ttc ||= TimeToComplete.new(completed)
    end

    def done_last30days
      @done_last30days ||= done_since(one_month)
    end

    def done_last12months
      @done_last12months ||= done_since(one_year)
    end

    def created_last30days
      @sum_actions_created_last30days ||= new_since(one_month)
    end

    def created_last12months
      @sum_actions_created_last12months ||= new_since(one_year)
    end

    def completion_charts
      @completion_charts ||= %w{
     actions_done_last30days_data
     actions_done_last12months_data
     actions_completion_time_data
      }.map do |action|
        Stats::Chart.new(action)
      end
    end

    def timing_charts
      @timing_charts ||= %w{
      actions_visible_running_time_data
      actions_running_time_data
      actions_open_per_week_data
      actions_day_of_week_all_data
      actions_day_of_week_30days_data
      actions_time_of_day_all_data
      actions_time_of_day_30days_data
      }.map do |action|
        Stats::Chart.new(action)
      end
    end

    private

    def one_year
      @one_year ||= 12.months.ago.beginning_of_day
    end

    def one_month
      @one_month ||= 1.month.ago.beginning_of_day
    end

    def new_since(cutoff)
      user.todos.created_after(cutoff).count
    end

    def done_since(cutoff)
      user.todos.completed.completed_after(cutoff).count
    end

    def completed
      @completed ||= user.todos.completed.select("completed_at, created_at")
    end
  end
end

w001/tracks/app/models/stats/chart.rb
module Stats

  class Chart

    attr_reader :action, :height, :width
    def initialize(action, dimensions = {})
      @action = action
      @height = dimensions.fetch(:height) { 250 }
      @width = dimensions.fetch(:width) { 460 }
    end

    def dimensions
      "#{width}x#{height}"
    end

  end

end

w001/tracks/app/controllers/stats_controller.rb
class StatsController < ApplicationController

  SECONDS_PER_DAY = 86400;

  helper :todos, :projects, :recurring_todos
  append_before_filter :init, :except => :index

  def index
    @page_title = t('stats.index_title')
    @hidden_contexts = current_user.contexts.hidden
    @stats = Stats::UserStats.new(current_user)
  end

  def actions_done_last12months_data
    # get actions created and completed in the past 12+3 months. +3 for running
    # - outermost set of entries needed for these calculations
    actions_last12months = current_user.todos.created_or_completed_after(@cut_off_year_plus3).select("completed_at,created_at")

    # convert to array and fill in non-existing months
    @actions_done_last12months_array = put_events_into_month_buckets(actions_last12months, 13, :completed_at)
    @actions_created_last12months_array = put_events_into_month_buckets(actions_last12months, 13, :created_at)

    # find max for graph in both arrays
    @max = (@actions_done_last12months_array + @actions_created_last12months_array).max

    # find running avg
    done_in_last_15_months = put_events_into_month_buckets(actions_last12months, 16, :completed_at)
    created_in_last_15_months = put_events_into_month_buckets(actions_last12months, 16, :created_at)

    @actions_done_avg_last12months_array = compute_running_avg_array(done_in_last_15_months, 13)
    @actions_created_avg_last12months_array = compute_running_avg_array(created_in_last_15_months, 13)

    # interpolate avg for current month.
    @interpolated_actions_created_this_month = interpolate_avg_for_current_month(@actions_created_last12months_array)
    @interpolated_actions_done_this_month = interpolate_avg_for_current_month(@actions_done_last12months_array)

    @created_count_array = Array.new(13, actions_last12months.created_after(@cut_off_year).count(:all)/12.0)
    @done_count_array    = Array.new(13, actions_last12months.completed_after(@cut_off_year).count(:all)/12.0)
    render :layout => false
  end

  def interpolate_avg_for_current_month(set)
    (set[0]*(1/percent_of_month) + set[1] + set[2]) / 3.0
  end

  def percent_of_month
    Time.zone.now.day / Time.zone.now.end_of_month.day.to_f
  end

  def actions_done_last_years
    @page_title = t('stats.index_title')
    @chart = Stats::Chart.new('actions_done_lastyears_data', :height => 400, :width => 900)
  end

  def actions_done_lastyears_data
    actions_last_months = current_user.todos.select("completed_at,created_at")

    month_count = difference_in_months(@today, actions_last_months.minimum(:created_at))
    # because this action is not scoped by date, the minimum created_at should always be
    # less than the minimum completed_at, so no reason to check minimum completed_at

    # convert to array and fill in non-existing months
    @actions_done_last_months_array = put_events_into_month_buckets(actions_last_months, month_count+1, :completed_at)
    @actions_created_last_months_array = put_events_into_month_buckets(actions_last_months, month_count+1, :created_at)

    # find max for graph in both hashes
    @max = (@actions_done_last_months_array + @actions_created_last_months_array).max

    # set running avg
    @actions_done_avg_last_months_array = compute_running_avg_array(@actions_done_last_months_array,month_count+1)
    @actions_created_avg_last_months_array = compute_running_avg_array(@actions_created_last_months_array,month_count+1)

    # interpolate avg for this month.
    @interpolated_actions_created_this_month = interpolate_avg_for_current_month(@actions_created_last_months_array)
    @interpolated_actions_done_this_month = interpolate_avg_for_current_month(@actions_done_last_months_array)

    @created_count_array = Array.new(month_count+1, actions_last_months.select { |x| x.created_at }.size/month_count)
    @done_count_array    = Array.new(month_count+1, actions_last_months.select { |x| x.completed_at }.size/month_count)

    render :layout => false
  end

  def actions_done_last30days_data
    # get actions created and completed in the past 30 days.
    @actions_done_last30days = current_user.todos.completed_after(@cut_off_30days).select("completed_at")
    @actions_created_last30days = current_user.todos.created_after(@cut_off_30days).select("created_at")

    # convert to array. 30+1 to have 30 complete days and one current day [0]
    @actions_done_last30days_array = convert_to_days_from_today_array(@actions_done_last30days, 31, :completed_at)
    @actions_created_last30days_array = convert_to_days_from_today_array(@actions_created_last30days, 31, :created_at)

    # find max for graph in both hashes
    @max = [@actions_done_last30days_array.max, @actions_created_last30days_array.max].max

    render :layout => false
  end

  def actions_completion_time_data
    @actions_completion_time = current_user.todos.completed.select("completed_at, created_at").reorder("completed_at DESC" )

    # convert to array and fill in non-existing weeks with 0
    @max_weeks = @actions_completion_time.last ? difference_in_weeks(@today, @actions_completion_time.last.completed_at) : 1
    @actions_completed_per_week_array = convert_to_weeks_running_array(@actions_completion_time, @max_weeks+1)

    # stop the chart after 10 weeks
    @count = [10, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_completion_time_array = cut_off_array_with_sum(@actions_completed_per_week_array, @count)
    @max_actions = @actions_completion_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_completion_time_array, @actions_completion_time.count(:all))

    render :layout => false
  end

  def actions_running_time_data
    @actions_running_time = current_user.todos.not_completed.select("created_at").reorder("created_at DESC")

    # convert to array and fill in non-existing weeks with 0
    @max_weeks = difference_in_weeks(@today, @actions_running_time.last.created_at)
    @actions_running_per_week_array = convert_to_weeks_from_today_array(@actions_running_time, @max_weeks+1, :created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_running_time_array = cut_off_array_with_sum(@actions_running_per_week_array, @count)
    @max_actions = @actions_running_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_running_time_array, @actions_running_time.count )

    render :layout => false
  end

  def actions_visible_running_time_data
    # running means
    # - not completed (completed_at must be null)
    # visible means
    # - actions not part of a hidden project
    # - actions not part of a hidden context
    # - actions not deferred (show_from must be null)
    # - actions not pending/blocked

    @actions_running_time = current_user.todos.not_completed.not_hidden.not_deferred_or_blocked.
      select("todos.created_at").
      reorder("todos.created_at DESC")

    @max_weeks = difference_in_weeks(@today, @actions_running_time.last.created_at)
    @actions_running_per_week_array = convert_to_weeks_from_today_array(@actions_running_time, @max_weeks+1, :created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_running_time_array = cut_off_array_with_sum(@actions_running_per_week_array, @count)
    @max_actions = @actions_running_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_running_time_array, @actions_running_time.count )

    render :layout => false
  end

  def actions_open_per_week_data
    @actions_started = current_user.todos.created_after(@today-53.weeks).
      select("todos.created_at, todos.completed_at").
      reorder("todos.created_at DESC")

    @max_weeks = difference_in_weeks(@today, @actions_started.last.created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    @actions_open_per_week_array = convert_to_weeks_running_from_today_array(@actions_started, @max_weeks+1)
    @actions_open_per_week_array = cut_off_array(@actions_open_per_week_array, @count)
    @max_actions = (@actions_open_per_week_array.max or 0)

    render :layout => false
  end

  def context_total_actions_data
    actions = Stats::TopContextsQuery.new(current_user).result

    @data = Stats::PieChartData.new(actions, t('stats.spread_of_actions_for_all_context'), 70)

    render :pie_chart_data, :layout => false
  end

  def context_running_actions_data
    actions = Stats::TopContextsQuery.new(current_user, :running => true).result
    @data = Stats::PieChartData.new(actions, t('stats.spread_of_running_actions_for_visible_contexts'), 60)

    render :pie_chart_data, :layout => false
  end

  def actions_day_of_week_all_data
    @actions_creation_day = current_user.todos.select("created_at")
    @actions_completion_day = current_user.todos.completed.select("completed_at")

    # convert to array and fill in non-existing days
    @actions_creation_day_array = Array.new(7) { |i| 0}
    @actions_creation_day.each { |t| @actions_creation_day_array[ t.created_at.wday ] += 1 }
    @max = @actions_creation_day_array.max

    # convert to array and fill in non-existing days
    @actions_completion_day_array = Array.new(7) { |i| 0}
    @actions_completion_day.each { |t| @actions_completion_day_array[ t.completed_at.wday ] += 1 }
    @max = @actions_completion_day_array.max

    render :layout => false
  end

  def actions_day_of_week_30days_data
    @actions_creation_day = current_user.todos.created_after(@cut_off_month).select("created_at")
    @actions_completion_day = current_user.todos.completed_after(@cut_off_month).select("completed_at")

w001/tracks/app/helpers/stats_helper.rb
module StatsHelper

  def font_size(cloud, tag)
    9 + 2 * cloud.relative_size(tag)
  end

  def month_and_year_label(i)
    t('date.month_names')[ (Time.zone.now.mon - i -1 ) % 12 + 1 ]+ " " + (Time.zone.now - i.months).year.to_s
  end

  def array_of_month_and_year_labels(count)
    Array.new(count) { |i| month_and_year_label(i) }
  end

  def month_label(i)
    t('date.month_names')[ (Time.zone.now.mon - i -1 ) % 12 + 1 ]
  end

  def array_of_month_labels(count)
    Array.new(count) { |i| month_label(i) }
  end

end

w001/tracks/app/views/stats/_actions.html.erb
<%= render :partial => 'time_to_complete', :locals => {:ttc => actions.ttc} -%>

<p><%= t('stats.actions_actions_avg_created_30days', :count => (actions.created_last30days*10.0/30.0).round/10.0 )%>
<%= t('stats.actions_avg_completed_30days', :count => (actions.done_last30days*10.0/30.0).round/10.0 )%>
<%= t('stats.actions_avg_created', :count => (actions.created_last12months*10.0/12.0).round/10.0 )%>
<%= t('stats.actions_avg_completed', :count => (actions.done_last12months*10.0/12.0).round/10.0 )%></p>

<% actions.completion_charts.each do |chart| %><%=
    render :partial => 'chart', :locals => {:chart => chart}
-%><% end %>

<br style="clear:both">

<% actions.timing_charts.each do |chart| %><%=
    render :partial => 'chart', :locals => {:chart => chart}
-%><% end %>

w001/tracks/app/views/stats/_projects.html.erb
<%= render :partial => 'projects_list', :locals => {:projects => projects.actions, :key => 'projects', :n => :count} -%>

<%= render :partial => 'projects_list', :locals => {:projects => projects.actions_last30days, :key => 'projects_30days', :n => :count} -%>

<%= render :partial => 'projects_list', :locals => {:projects => projects.runtime, :key => 'longrunning', :n => :running_time, :i18n_key => "days_midsentence"} -%>

w001/tracks/app/views/stats/_projects_list.html.erb
<%- i18n_key ||= "actions_midsentence" -%>
<div class="stats_module">
  <h3><%= t("stats.top10_#{key}") %></h3>
  <% projects.each_with_index do |p, i| -%>
    <%= i + 1 -%> - <%= link_to p.name, project_path(p) %> (<%=p.send(n)%> <%= t("common.#{i18n_key}", :count => p.send(n)) %>) <br/>
  <% end -%>
  <%= render :partial => 'null_list_item', :locals => {:from => projects.size + 1, :to => 10} -%>
</div>

w001/tracks/app/views/stats/_tags.html.erb
<div class="stats_module">
<h3><%= t("stats.tag_cloud#{key}_title") %></h3>
<p><%= t("stats.tag_cloud#{key}_description") %></p>
<p>
<%
  if tag_cloud.empty?
    t('stats.no_tags_available')
  else
    tag_cloud.tags.each do |t|
%> <%=
      link_to t.name, tag_path(t.name), {
        :style => "font-size: " + "#{font_size(tag_cloud, t)}pt",
        :title => "#{t.count} #{t('common.actions_midsentence', :count => t.count)}"}
-%> <%
      end
    end
-%>
</p>
</div>

w001/tracks/app/views/stats/actions_completion_time_data.html.erb
<%-
time_labels         = Array.new(@count){ |i| "#{i}-#{i+1}" }
time_labels[0]      = t('stats.within_one')
time_labels[@count] = "> #{@count}"
-%>
&title=<%= t('stats.action_completion_time_title') %>,{font-size:16},&
&y_legend=<%= t('stats.legend.actions') %>,10,0x8010A0&
&y2_legend=<%= t('stats.legend.percentage') %>,10,0xFF0000&
&x_legend=<%= t('stats.legend.running_time') %>,12,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0&
&values=<%= @actions_completion_time_array.join(",")%>&
&line_2=2,0xFF0000&
&values_2=<%= @cum_percent_done.join(",")%>&
&x_labels=<%= time_labels.join(",")%>&
&y_min=0&
<%
# add one to @max for people who have no actions completed yet.
# OpenFlashChart cannot handle y_max=0
-%>
&y_max=<%=1+@max_actions+@max_actions/10-%>&
&show_y2=true&
&y2_lines=2&
&y2_min=0&
&y2_max=100&
&x_label_style=9,,2,1&

w001/tracks/app/views/stats/actions_day_of_week_30days_data.html.erb
&title=<%= t('stats.actions_dow_30days_title') %>,{font-size:16},&
&y_legend=<%= t('stats.actions_dow_30days_legend.number_of_actions') %>,10,0x736AFF&
&x_legend=<%= t('stats.actions_dow_30days_legend.day_of_week') %>,10,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0,<%= t('stats.labels.created') %>,8&
&filled_bar_2=50,0x0066CC,0x0066CC,<%= t('stats.labels.completed') %>,8&
&values=<%=  @actions_creation_day_array.join(",") %>&
&values_2=<%= @actions_completion_day_array.join(",") %>&
&x_labels=<%= t('date.day_names').join(",") %>&
&y_min=0&
<%
  # add one to @max for people who have no actions completed yet.
  # OpenFlashChart cannot handle y_max=0
-%>
&y_max=<%=@max+1 -%>&
&x_label_style=9,,2,1&

w001/tracks/app/views/stats/actions_day_of_week_all_data.html.erb
&title=<%= t('stats.actions_day_of_week_title') %>,{font-size:16},&
&y_legend=<%= t('stats.actions_day_of_week_legend.number_of_actions') %>,10,0x736AFF&
&x_legend=<%= t('stats.actions_day_of_week_legend.day_of_week') %>,10,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0,<%= t('stats.labels.created') %>,8&
&filled_bar_2=50,0x0066CC,0x0066CC,<%= t('stats.labels.completed') %>,8&
&values=<%=  @actions_creation_day_array.join(",") %>&
&values_2=<%= @actions_completion_day_array.join(",") %>&
&x_labels=<%= t('date.day_names').join(",") %>&
&y_min=0&
<%
  # add one to @max for people who have no actions completed yet.
  # OpenFlashChart cannot handle y_max=0
-%>
&y_max=<%=@max+1 -%>&
&x_label_style=9,,2,1&

w001/tracks/app/views/stats/actions_done_last12months_data.html.erb
<%-
    url = url_for :controller => 'stats', :action => 'actions_done_last_years'
-%>
&title=<%= t('stats.actions_lastyear_title') %>,{font-size:16},&
&y_legend=<%= t('stats.legend.number_of_actions') %>,12,0x736AFF&
&x_legend=<%= t('stats.legend.months_ago') %>,12,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0,<%= t('stats.labels.created')%>,9&
&filled_bar_2=50,0x0066CC,0x0066CC,<%= t('stats.labels.completed') %>,9&
&line_3=2,0x00FF00, <%= t('stats.labels.avg_created') %>, 9&
&line_4=2,0xFF0000, <%= t('stats.labels.avg_completed') %>, 9&
&line_5=2,0x007700, <%= t('stats.labels.month_avg_created', :months => 3) %>, 9&
&line_6=2,0xAA0000, <%= t('stats.labels.month_avg_completed', :months => 3) %>, 9&
&line_7=1,0xAA0000&
&line_8=1,0x007700&
&values=<%=   @actions_created_last12months_array.join(",")%>&
&links=<%=    Array.new(13,url).join(",") %>&
&links_2=<%=  Array.new(13,url).join(",") %>&
&values_2=<%= @actions_done_last12months_array.join(",")%>&
&values_3=<%= @created_count_array.join(",")%>&
&values_4=<%= @done_count_array.join(",")%>&
&values_5=<%= @actions_created_avg_last12months_array.join(",")%>&
&values_6=<%= @actions_done_avg_last12months_array.join(",")%>&
&values_7=<%= @interpolated_actions_created_this_month%>,<%=@actions_done_avg_last12months_array[1]%>&
&values_8=<%= @interpolated_actions_done_this_month%>,<%=@actions_created_avg_last12months_array[1]%>&
&x_labels=<%= array_of_month_labels(@done_count_array.size).join(",")%>&
&y_min=0&
<% # add one to @max for people who have no actions completed yet.
   # OpenFlashChart cannot handle y_max=0 -%>
&y_max=<%=@max+@max/10+1-%>&
&x_label_style=9,,2,&

w001/tracks/app/views/stats/actions_time_of_day_30days_data.html.erb
&title=<%= t('stats.tod30') %>,{font-size:16},&
&y_legend=<%= t('stats.tod30_legend.number_of_actions') %>,12,0x736AFF&
&x_legend=<%= t('stats.tod30_legend.time_of_day') %>,12,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0,<%= t('stats.labels.created') %>,8&
&filled_bar_2=50,0x0066CC,0x0066CC,<%= t('stats.labels.completed') %>,8&
&values=<%
0.upto 22 do |i| -%>
  <%=@actions_creation_hour_array[i] -%>,
<% end -%><%=@actions_creation_hour_array[23]%>&
&values_2=<%
0.upto 22 do |i| -%>
  <%=@actions_completion_hour_array[i] -%>,
<% end -%><%=@actions_completion_hour_array[23]%>&
&x_labels= <%
0.upto 22 do |i| -%>
  <%=i-%>,
<% end -%>23&
&y_min=0&
<% # add one to @max for people who have no actions completed yet.
   # OpenFlashChart cannot handle y_max=0 -%>
&y_max=<%=@max+1 -%>&
&x_label_style=9,,1,1&

w001/tracks/app/views/stats/pie_chart_data.html.erb
&title=<%= @data.title %>,{font-size:16}&
&pie=<%= @data.alpha %>,#505050,{font-size: 12px; color: #404040;}&
&x_axis_steps=1& &y_ticks=5,10,5& &line=3,#87421F& &y_min=0& &y_max=20&
&values=<%=     @data.values.join(",") %>&
&pie_labels=<%= @data.labels.join(",") %>&
&links=<%=      @data.ids.map{|id| context_path(id)}.join(",") %>&
&colours=#d01f3c,#356aa0,#C79810,#c61fd0,#1fc6d0,#1fd076,#72d01f,#c6d01f,#d0941f,#40941f&
&tool_tip=#x_label#: #val#%25&
&x_label_style=9,,2,1&